In [1]:
import random
sys.path.append("../..")
from thesis.utils.utils import RewardCheck
#from thesis.envs.matrix_dispatching_zoo_death import MatrixDispatchingMA_Death
import numpy as np

In [2]:
from thesis.envs.matrix import Matrix

In [3]:
env = Matrix(
    model_path = "../../envs/MiniMatrix_.zip",
    startport = 51146,
    fleetsize = 6,
    max_fleetsize = 10,
    max_seconds = 5*60,
    pseudo_dispatcher = False,
    routing_agent_death=True,
    sim_config = dict(
        dispatch = True,
        routing_ma = True,
        dispatching_ma = True,
        reward_removed_for_block = -1
    )
)

c:\Users\Wegma\.conda\envs\thesis\lib\site-packages\alpyne\client\utils.py:124: UserWarning: Unzipping to temporary directory (C:\Users\Wegma\AppData\Local\Temp\alpyne_85827_nk7d8ysw)
  warn(f"Unzipping to temporary directory ({tmp_dir})")


In [4]:
env.agents

['0', '1', '2', '3', '4', '5', '1000', '1001', '1002', '1003', '1004', '1005']

In [5]:
env.observation_space("5")

Dict(action_mask:Box([[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]], [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]], (10, 5), float32), agvs:Box([[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 

In [17]:
env.agent_behaviors

{'0': <thesis.envs.behaviors.MultiAgent at 0x2027ef134c0>,
 '1': <thesis.envs.behaviors.MultiAgent at 0x2027ef13550>,
 '2': <thesis.envs.behaviors.MultiAgent at 0x2027ef135e0>,
 '3': <thesis.envs.behaviors.MultiAgent at 0x2027ef13670>,
 '4': <thesis.envs.behaviors.MultiAgent at 0x2027ef13700>,
 '5': <thesis.envs.behaviors.MultiAgent at 0x2027ef13790>,
 '1000': <thesis.envs.behaviors.MultiAgent at 0x2027ef13820>,
 '1001': <thesis.envs.behaviors.MultiAgent at 0x2027ef138b0>,
 '1002': <thesis.envs.behaviors.MultiAgent at 0x2027ef13940>,
 '1003': <thesis.envs.behaviors.MultiAgent at 0x2027ef139d0>,
 '1004': <thesis.envs.behaviors.MultiAgent at 0x2027ef13a60>,
 '1005': <thesis.envs.behaviors.MultiAgent at 0x2027ef13af0>,
 '6': <thesis.envs.behaviors.MultiAgent at 0x2027f076fd0>,
 '7': <thesis.envs.behaviors.MultiAgent at 0x2027f0c7160>,
 '8': <thesis.envs.behaviors.MultiAgent at 0x2027ee946d0>,
 '9': <thesis.envs.behaviors.MultiAgent at 0x2027ee88d00>,
 '10': <thesis.envs.behaviors.MultiAge

In [15]:
chk = RewardCheck(env, obs2action = lambda a, b: ([random.randint(1,4) for i in range(10)],""))

In [16]:
chk.run(1, seed = 6)

0---1005--------------------
OLD: [0, 0] 	 done:0
OLD: curr: [0, 0]	 next:[0, 0]	 tar:[0, 0]
ACTION: 0
NEW: [[1.         0.42045455 0.86       0.42045455 0.86       0.32954545
  0.808      0.42045455 0.76       0.47727273 0.86       0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.        ]
 [1.         0.32954545 0.808      0.32954545 0.808      0.
  0.         0.         0.         0.42045455 0.86       0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.        ]] 	 done:False
NEW: curr: [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]	 next:[[0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.    